// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vimtkbhzbyslwytregdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbXRrYmh6YnlzbHd5dHJlZ2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjk5NzgsImV4cCI6MjA3MjgwNTk3OH0.hX7bLc2gn6uIH1UaEbq9bKJSgE504lAMUg1etlBFu8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});